# Generated by Django 4.2.23 on 2025-08-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.TextField()),
                ("user_name", models.TextField()),
                ("student_id", models.TextField()),
                ("password", models.TextField()),
                ("type", models.TextField()),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
    ]
