"""
Django settings for Question_Answering_System project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o2@ylmhw@t5=!%4l3d**vi0dvebtb5og#rixklwolza=7z21#8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # 开发环境使用True

ALLOWED_HOSTS = ['*'] # 允许访问的主机名或ip地址


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'questionAnswer',
    "userfunctions",
    'sendEmail',
    'learningPath',
    'wordCloud',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Question_Answering_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Question_Answering_System.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Question Answering System',         # 数据库名称
        'USER': 'postgres',     # 数据库用户名
        'PASSWORD': '159357',    # 数据库密码
        'HOST': 'localhost',          # 数据库地址（如果是本地，则为localhost）
        'PORT': '5432',                   # 数据库端口（默认留空，使用默认端口5432）
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 生产环境使用
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 开发时使用，邮件打印到控制台

EMAIL_HOST = 'smtp.163.com'  # 邮件服务器地址
EMAIL_PORT = 465  # 端口号
EMAIL_USE_TLS = False  # TLS加密
EMAIL_USE_SSL = True  # SSL加密
EMAIL_HOST_USER = 'pai18110382618@163.com'  # 发件邮箱
EMAIL_HOST_PASSWORD = 'FFb8g357ziBqjVRi'  # 邮箱密码或授权码
DEFAULT_FROM_EMAIL = 'pai18110382618@163.com'  # 默认发件人

# 老师邮箱
TEACHER_EMAIL=["1712269587@qq.com"]

# api调用
LLM_CONFIG = {
    'API_KEY':"sk-b73a7f714f8c4af789d3bc5abe00241e",
    "API_URL": "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation" ,
    # "Model": "deepseek-r1"，
    "Model": "qwen-plus",
    # "Model":"qwen-turbo"
}

# 词云停用词
STOPWORDS = {"我们", "他们", "它们", "查找"}

USE_TZ = False #禁用时区支持

#  (使用 Redis 作为缓存后端)
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#     }
# }
